- .gitignore
- app.js
- package-lock.json
- package.json
> setup mern

- frontend/src/components/nav/navbar.js
- frontend/src/reducers/root_reducer.js
> Frontend fixes

- .gitignore
- app.js
- config/keys_prod.js
- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/components/root.jsx
- frontend/yarn.lock
successfully deployed to heroku
[live](https://fieldlily.herokuapp.com/#/)
This is going to have all sorts of merge conflicts with the concurrently-developed `frontend` feature branch.
@per-pro, you were assigned on this just as a heads up about those conflicts, if you're close to done I can re-base this branch off of yours, otherwise I can merge in any changes when you submit your pull request.
> Heroku deployment

- LICENSE
> update copyright owners to be the full team

- frontend/src/components/root.jsx
app isn't being rendered on main, this fixes that
> remove placeholder text & render epp

- frontend/src/reducers/session_reducer.js
> add RECEIVE_CURRENT_USER case to session reducer

- routes/api/users.js
we had a `/test` route in our user api that we don't really need anymore
> remove test route from user api

- routes/api/habits.js
- routes/api/resources.js
- routes/api/utils.js
updating store with reducers will go from O(n) to O(1) with this update
> change response arrays to object keyed by ids

- frontend/src/actions/modal_actions.js
- frontend/src/components/modal/modal.css
- frontend/src/components/modal/modal.jsx
- frontend/src/components/modal/modal_container.js
- frontend/src/components/modal/modal_manifest.js
- frontend/src/components/nav/navbar.js
- frontend/src/components/nav/navbar_container.js
- frontend/src/reducers/modal_reducer.js
- frontend/src/reducers/root_reducer.js
- frontend/src/reducers/ui_reducer.js
sets up authentication to be via a modal
> auth modal

- frontend/src/components/habits/habit_box.js
- frontend/src/components/habits/habits.js
- frontend/src/components/habits/habits_container.js
require authentication to edit habits or post new ones
> Habit require auth

- frontend/src/components/habits/habits.css
- frontend/src/components/habits/habits.js
makes the habits show a sorta nasty shade of olive so I'm going to have to change that, but it's some color styling, so.
> preliminary habit index coloring

- frontend/src/components/habits/habit_box.css
- frontend/src/components/habits/habit_box.js
- frontend/src/components/habits/habits.css
- frontend/src/components/habits/habits.js
some preliminary styling for the frontend habits index
> Habit styling

- frontend/src/components/resources/resources.jsx
- frontend/src/components/resources/resources_container.js
fix for the issue seen in the code review
> hotfix `resources.jsx` prop to be map-able

- frontend/src/actions/habit_actions.js
- frontend/src/components/profile/profile.js
- frontend/src/components/profile/profile_container.js
- frontend/src/reducers/entities/habits_reducer.js
- frontend/src/util/habit_api_util.js
habits are part of the entities reducer so this fixes an issue where heroku breaks if a user tries to view their profile
> profile frontend fixes

- frontend/src/actions/resource_actions.js
- frontend/src/components/app.js
- frontend/src/components/resources/resource_index_item.jsx
- frontend/src/components/resources/resource_show.jsx
- frontend/src/components/resources/resource_show_container.jsx
- frontend/src/components/resources/resources.jsx
- frontend/src/reducers/entities/resources_reducer.js
various fixes to errors from resources as outlined in the individual commits
> Resources fixes

- frontend/src/components/app.js
- frontend/src/components/habits/habit_update.js
- frontend/src/components/habits/habits.js
- frontend/src/reducers/modal_reducer.js
- frontend/src/reducers/session_reducer.js
app.js
LoginFormContainer and SignupFormContainer were not being used
habit_update.js
HabitBox was not being used
habits.js
constructor did nothing (useless constructor warnings)
modal_reducer.js
anonymous function export
session_reducer.js
anonymous function export
> resolve all linter warnings

- frontend/public/fonts.css
- frontend/public/manifest.css
- frontend/src/components/nav/navbar.css
[Reggae One by Fontworks Inc](https://fonts.google.com/specimen/Reggae+One?preview.text_type=custom#about) looks pretty good on the navbar icon's placeholder text, for now
> adding new font

- frontend/src/components/nav/navbar.css
- frontend/src/components/nav/navbar_logo_animation.css
people weren't seeing that there was an interactive pop-up sort of thing before (ie. bad design)
> add animation to draw user attention to interact

- frontend/src/components/app.js
- frontend/src/components/footer/footer.css
- frontend/src/components/footer/footer.jsx
- frontend/src/components/main/main_page.js
- frontend/src/components/nav/navbar.css
- frontend/src/components/nav/navbar.js
- remove placeholder text from main page
- improve footer (which currently still has placeholder copyright notice, which is slightly off)
- put nav links in buttons (which still need styling)
there's a few things this branch still needs to resolve:
1. button styling needs to be uniform
2. about page needs to exist
> Main and nav cleanup

- frontend/src/components/nav/navbar.css
put links inside buttons
make buttons turn to pointers in the nav
add some styling to the buttons
> button madness in the nav!

- frontend/src/components/habits/habit_compose.js
- frontend/src/components/nav/navbar.css
fix regression error where users could no longer post new habits
> some styling and huge bugfix

- frontend/src/components/session/signup_form_container.js
> add action to signup component for demo login

- frontend/src/actions/resource_actions.js
- frontend/src/components/resources/resource_form.jsx
- frontend/src/components/resources/resource_form_container.js
- frontend/src/reducers/entities/resources_reducer.js
Reverts JamesKoenig/FieldLily#93
> Revert "Modal v2" to amend 

- frontend/src/actions/resource_actions.js
- frontend/src/components/resources/resource_form.jsx
- frontend/src/components/resources/resource_form_container.js
- frontend/src/reducers/entities/resources_reducer.js
Reverts JamesKoenig/FieldLily#94
nevermind
> Revert "Revert "Modal v2" to amend "

- frontend/public/colors/colors.css
- frontend/public/colors/royal-sunset.css
- frontend/src/components/habits/habit_box.css
- frontend/src/components/habits/habits.css
> Color work

- frontend/src/components/habits/habit_show_container.jsx
> fix case from before when habit resources are pulled

- frontend/src/components/habits/habit_show.css
- frontend/src/components/habits/habit_show.jsx
- frontend/src/components/resources/resource_index_item.css
- frontend/src/components/resources/resource_index_item.jsx
- frontend/src/components/resources/resource_show.css
- frontend/src/components/resources/resource_show.jsx
redo some styling on links, remove some superfluous <br/>, add some
necessary styling tags for things to still have _some_ container backgrounds
Fixes #105
> make the background consistent (as per #105)

- frontend/src/actions/habit_actions.js
- frontend/src/actions/modal/confirmation_modal_actions.js
- frontend/src/components/habits/habit_delete_confirmation.css
- frontend/src/components/habits/habit_delete_confirmation.jsx
- frontend/src/components/habits/habit_show.jsx
- frontend/src/components/habits/habit_show_container.jsx
- frontend/src/components/modal/modal_manifest.js
- frontend/src/reducers/entities/habits_reducer.js
- frontend/src/reducers/modal/misc_reducer.js
- frontend/src/reducers/modal/status_reducer.js
- frontend/src/reducers/modal/subtype_reducer.js
- frontend/src/reducers/modal/type_reducer.js
- frontend/src/util/habit_api_util.js
resolves #106
resolves #112 
REQUIRES STYLING
> Delete habit button & confirmation modal

- frontend/src/components/habits/habit_box.js
- frontend/src/components/habits/habit_show.jsx
- frontend/src/components/habits/habit_show_container.jsx
- frontend/src/components/habits/habits.js
- frontend/src/components/habits/habits_container.js
> move edit button out of index list

- frontend/src/actions/modal/resource_modal_actions.js
- frontend/src/actions/resource_actions.js
- frontend/src/components/habits/habit_show.jsx
- frontend/src/components/resources/resource_form.jsx
- frontend/src/components/resources/resource_form_container.js
- frontend/src/reducers/entities/resources_reducer.js
- frontend/src/reducers/modal/misc_reducer.js
- routes/api/resources.js
> add the ability to create resources to the frontend

- frontend/src/components/habits/habit_compose.js
- frontend/src/components/habits/habit_compose_container.js
- frontend/src/components/habits/habit_delete_confirmation.jsx
- frontend/src/components/modal/modal_container.js
still needs to do so purely on success, though
> fix modal fade out on submit

- frontend/src/actions/modal/confirmation_modal_actions.js
- frontend/src/actions/modal/resource_modal_actions.js
- frontend/src/components/habits/habit_compose.js
- frontend/src/components/habits/habit_delete_confirmation.jsx
- frontend/src/components/habits/habit_show.jsx
- frontend/src/components/modal/confirm_delete.css
- frontend/src/components/modal/confirm_delete.jsx
- frontend/src/components/modal/modal_manifest.js
- frontend/src/components/resources/resource_delete_confirmation.jsx
- frontend/src/components/resources/resource_form.jsx
- frontend/src/components/resources/resource_form_container.js
- frontend/src/components/resources/resource_show.jsx
- frontend/src/components/resources/resource_show_container.jsx
- frontend/src/reducers/modal/misc_reducer.js
- frontend/src/reducers/modal/subtype_reducer.js
- frontend/src/util/resources_api_util.js
fixes resource edit and delete, but these still need to be hidden unless the user is authorized
> Resource delete edit buttons

- frontend/package-lock.json
- frontend/package.json
- frontend/src/store/store.js
same as #140 but without superfluous commits from other features branches, via cherry-picking
> Itai's Redux Logger as dev-dependency changes

- frontend/src/actions/session_actions.js
- frontend/src/components/session/login_form.js
- frontend/src/components/session/login_form_container.js
- frontend/src/components/session/signup_form.js
- frontend/src/components/session/signup_form_container.js
- frontend/src/reducers/session_errors_reducer.js
there's some whitespace changes along with this (deleting trailing whitespace characters,
> clear auth errors upon close of auth form

- frontend/src/components/footer/footer.jsx
- frontend/src/components/profile/profile.js
do not merge this pull request until a discussion is had about removing the profile
> remove footer "about us" link, unbreak profile

- frontend/src/components/common-stylings/entity-index-item.css
- frontend/src/components/habits/habit_compose.css
- frontend/src/components/habits/habit_show.css
- frontend/src/components/modal/confirm_delete.css
- frontend/src/components/modal/modal.css
- frontend/src/components/nav/navbar.css
- frontend/src/components/resources/resource_form.css
- frontend/src/components/resources/resource_form.jsx
- frontend/src/components/session/session.css
cherry-picked version isolating the changes outlined in #147 from its previous feature branches
> Forms css extracted

- frontend/src/actions/display_actions.js
- frontend/src/components/app.js
- frontend/src/components/common-stylings/entity-index.css
- frontend/src/components/habits/habit_box.js
- frontend/src/components/habits/habit_box_container.js
- frontend/src/components/habits/habit_box_style.js
- frontend/src/components/habits/habit_show.css
- frontend/src/components/habits/habit_show.jsx
- frontend/src/components/habits/habit_show_page.jsx
- frontend/src/components/habits/habits.js
- frontend/src/components/habits/habits_page.js
- frontend/src/components/main/main.jsx
- frontend/src/components/main/main_container.js
- frontend/src/components/main/main_entity.jsx
- frontend/src/components/main/main_entity_container.js
- frontend/src/components/main/stylings.js
- frontend/src/components/modal/modal.css
- frontend/src/components/nav/navbar.css
- frontend/src/components/nav/navbar.js
- frontend/src/components/profile/profile.js
- frontend/src/index.js
- frontend/src/reducers/display_reducer.js
- frontend/src/reducers/ui_reducer.js
setting up the app to be more streamlined
> Single page
